artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/191ZU2KRF5oVyi3ahqZRwY-h9XgxrAlWc/view?usp=share_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion